CREATE DATABASE alien;
USE alien;

-- user TABLE
CREATE TABLE user
(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  nick VARCHAR(35) UNIQUE NOT NULL,
  name VARCHAR(20) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  passwd CHAR(199) NOT NULL,
  img BLOB NOT NULL,
  root BIT NOT NULL DEFAULT 0
);

-- blog TABLE
CREATE TABLE blog
(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(30) NOT NULL,
  img BLOB NOT NULL,
  body TEXT NOT NULL,
  descripcion VARCHAR(500) NOT NULL,
  author VARCHAR(35) NOT NULL
);
